Search.appendIndex(
    [
                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account",
            "name": "Account",
            "summary": "Represents\u0020an\u0020account\u0020on\u0020a\u0020CardDAV\u0020Server.",
            "url": "classes/MStilkerich-CardDavClient-Account.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020a\u0020new\u0020Account\u0020object.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003AconstructFromArray\u0028\u0029",
            "name": "constructFromArray",
            "summary": "Constructs\u0020an\u0020Account\u0020object\u0020from\u0020an\u0020array\u0020representation.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method_constructFromArray"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "Allows\u0020to\u0020serialize\u0020an\u0020Account\u0020object\u0020to\u0020JSON.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method_jsonSerialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "Provides\u0020a\u0020CardDavClient\u0020object\u0020to\u0020interact\u0020with\u0020the\u0020server\u0020for\u0020this\u0020account.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method_getClient"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003AgetDiscoveryUri\u0028\u0029",
            "name": "getDiscoveryUri",
            "summary": "Returns\u0020the\u0020discovery\u0020URI\u0020for\u0020this\u0020Account.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method_getDiscoveryUri"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003AsetUrl\u0028\u0029",
            "name": "setUrl",
            "summary": "Set\u0020the\u0020base\u0020URL\u0020of\u0020this\u0020account\u0020once\u0020the\u0020service\u0020URL\u0020has\u0020been\u0020discovered.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method_setUrl"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "Returns\u0020the\u0020base\u0020URL\u0020of\u0020the\u0020CardDAV\u0020service.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method_getUrl"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Provides\u0020a\u0020readable\u0020form\u0020of\u0020the\u0020core\u0020properties\u0020of\u0020the\u0020Account.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method___toString"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003AfindCurrentUserPrincipal\u0028\u0029",
            "name": "findCurrentUserPrincipal",
            "summary": "Queries\u0020the\u0020given\u0020URI\u0020for\u0020the\u0020current\u002Duser\u002Dprincipal\u0020property.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method_findCurrentUserPrincipal"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003AfindAddressbookHome\u0028\u0029",
            "name": "findAddressbookHome",
            "summary": "Queries\u0020the\u0020given\u0020URI\u0020for\u0020the\u0020CARDDAV\u003Aaddressbook\u002Dhome\u002Dset\u0020property.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#method_findAddressbookHome"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Account.html#property_username"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Account.html#property_password"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003A\u0024discoveryUri",
            "name": "discoveryUri",
            "summary": "URI\u0020originally\u0020used\u0020to\u0020discover\u0020the\u0020account.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#property_discoveryUri"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Account\u003A\u003A\u0024baseUrl",
            "name": "baseUrl",
            "summary": "URL\u0020of\u0020the\u0020discovered\u0020CardDAV\u0020server,\u0020with\u0020empty\u0020path.\u0020May\u0020be\u0020null\u0020if\u0020not\u0020discovered\u0020yet.",
            "url": "classes/MStilkerich-CardDavClient-Account.html#property_baseUrl"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection",
            "name": "AddressbookCollection",
            "summary": "Objects\u0020of\u0020this\u0020class\u0020represent\u0020an\u0020addressbook\u0020collection\u0020on\u0020a\u0020WebDAV\u0020server.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Returns\u0020a\u0020displayname\u0020for\u0020the\u0020addressbook.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_getName"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Provides\u0020a\u0020stringified\u0020representation\u0020of\u0020this\u0020addressbook\u0020\u0028name\u0020and\u0020URI\u0029.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method___toString"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AgetDetails\u0028\u0029",
            "name": "getDetails",
            "summary": "Provides\u0020the\u0020details\u0020for\u0020this\u0020addressbook\u0020as\u0020printable\u0020text.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_getDetails"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AsupportsMultiGet\u0028\u0029",
            "name": "supportsMultiGet",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_supportsMultiGet"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AgetCTag\u0028\u0029",
            "name": "getCTag",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_getCTag"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AgetCard\u0028\u0029",
            "name": "getCard",
            "summary": "Retrieves\u0020an\u0020address\u0020object\u0020from\u0020the\u0020addressbook\u0020collection\u0020and\u0020parses\u0020it\u0020to\u0020a\u0020VObject.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_getCard"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AdeleteCard\u0028\u0029",
            "name": "deleteCard",
            "summary": "Deletes\u0020a\u0020VCard\u0020from\u0020the\u0020addressbook.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_deleteCard"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AcreateCard\u0028\u0029",
            "name": "createCard",
            "summary": "Creates\u0020a\u0020new\u0020VCard\u0020in\u0020the\u0020addressbook.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_createCard"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AupdateCard\u0028\u0029",
            "name": "updateCard",
            "summary": "Updates\u0020an\u0020existing\u0020VCard\u0020of\u0020the\u0020addressbook.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_updateCard"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Issues\u0020an\u0020addressbook\u002Dquery\u0020report.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_query"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AshortenXmlNamespacesForPrinting\u0028\u0029",
            "name": "shortenXmlNamespacesForPrinting",
            "summary": "This\u0020function\u0020replaces\u0020some\u0020well\u002Dknown\u0020XML\u0020namespaces\u0020with\u0020a\u0020long\u0020name\u0020with\u0020shorter\u0020names\u0020for\u0020printing.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_shortenXmlNamespacesForPrinting"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AvalidateCard\u0028\u0029",
            "name": "validateCard",
            "summary": "Validates\u0020a\u0020VCard\u0020before\u0020sending\u0020it\u0020to\u0020a\u0020CardDAV\u0020server.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_validateCard"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003AgetNeededCollectionPropertyNames\u0028\u0029",
            "name": "getNeededCollectionPropertyNames",
            "summary": "Provides\u0020the\u0020list\u0020of\u0020property\u0020names\u0020that\u0020should\u0020be\u0020requested\u0020upon\u0020call\u0020of\u0020refreshProperties\u0028\u0029.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_getNeededCollectionPropertyNames"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\AddressbookCollection\u003A\u003APROPNAMES",
            "name": "PROPNAMES",
            "summary": "List\u0020of\u0020properties\u0020to\u0020query\u0020in\u0020refreshProperties\u0028\u0029\u0020and\u0020returned\u0020by\u0020getProperties\u0028\u0029.",
            "url": "classes/MStilkerich-CardDavClient-AddressbookCollection.html#constant_PROPNAMES"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient",
            "name": "CardDavClient",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AsyncCollection\u0028\u0029",
            "name": "syncCollection",
            "summary": "Note\u003A\u0020Google\u0027s\u0020server\u0020does\u0020not\u0020accept\u0020an\u0020empty\u0020syncToken,\u0020though\u0020explicitly\u0020allowed\u0020for\u0020initial\u0020sync\u0020by\u0020RFC6578.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_syncCollection"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AgetResource\u0028\u0029",
            "name": "getResource",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_getResource"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AgetAddressObject\u0028\u0029",
            "name": "getAddressObject",
            "summary": "Fetches\u0020an\u0020address\u0020object.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_getAddressObject"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AdeleteResource\u0028\u0029",
            "name": "deleteResource",
            "summary": "Requests\u0020the\u0020server\u0020to\u0020delete\u0020the\u0020given\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_deleteResource"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AupdateResource\u0028\u0029",
            "name": "updateResource",
            "summary": "Requests\u0020the\u0020server\u0020to\u0020update\u0020the\u0020given\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_updateResource"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AcreateResource\u0028\u0029",
            "name": "createResource",
            "summary": "Requests\u0020the\u0020server\u0020to\u0020create\u0020the\u0020given\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_createResource"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AmultiGet\u0028\u0029",
            "name": "multiGet",
            "summary": "Issues\u0020an\u0020addressbook\u002Dmultiget\u0020request\u0020to\u0020the\u0020server.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_multiGet"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Issues\u0020an\u0020addressbook\u002Dquery\u0020report.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_query"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AdetermineReqCardProps\u0028\u0029",
            "name": "determineReqCardProps",
            "summary": "Builds\u0020a\u0020CARDDAV\u003A\u003Aaddress\u002Ddata\u0020element\u0020with\u0020the\u0020requested\u0020properties.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_determineReqCardProps"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AfindProperties\u0028\u0029",
            "name": "findProperties",
            "summary": "Retrieves\u0020a\u0020set\u0020of\u0020WebDAV\u0020properties\u0020for\u0020a\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_findProperties"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AaddRequiredVCardProperties\u0028\u0029",
            "name": "addRequiredVCardProperties",
            "summary": "Adds\u0020required\u0020VCard\u0020properties\u0020to\u0020a\u0020set\u0020specified\u0020by\u0020the\u0020user.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_addRequiredVCardProperties"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AassertHttpStatus\u0028\u0029",
            "name": "assertHttpStatus",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_assertHttpStatus"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AcheckAndParseXMLMultistatus\u0028\u0029",
            "name": "checkAndParseXMLMultistatus",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_checkAndParseXMLMultistatus"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003ArequestWithRedirectionTarget\u0028\u0029",
            "name": "requestWithRedirectionTarget",
            "summary": "Performs\u0020a\u0020WebDAV\u0020request,\u0020automatically\u0020following\u0020redirections\u0020and\u0020providing\u0020the\u0020final\u0020target\u0020with\u0020the\u0020result.",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_requestWithRedirectionTarget"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AabsoluteUrl\u0028\u0029",
            "name": "absoluteUrl",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_absoluteUrl"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AconcatUrl\u0028\u0029",
            "name": "concatUrl",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_concatUrl"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AcompareUrlPaths\u0028\u0029",
            "name": "compareUrlPaths",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_compareUrlPaths"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AgetParserService\u0028\u0029",
            "name": "getParserService",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#method_getParserService"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003AMAP_NS2PREFIX",
            "name": "MAP_NS2PREFIX",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#constant_MAP_NS2PREFIX"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003A\u0024base_uri",
            "name": "base_uri",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#property_base_uri"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\CardDavClient\u003A\u003A\u0024httpClient",
            "name": "httpClient",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-CardDavClient.html#property_httpClient"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Config",
            "name": "Config",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Config.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Config\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Config.html#method_init"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Config\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Config.html#property_logger"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Config\u003A\u003A\u0024httplogger",
            "name": "httplogger",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Config.html#property_httplogger"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Exception\\ClientException",
            "name": "ClientException",
            "summary": "Implementation\u0020of\u0020PSR\u002D18\u0020ClientExceptionInterface.",
            "url": "classes/MStilkerich-CardDavClient-Exception-ClientException.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Exception\\NetworkException",
            "name": "NetworkException",
            "summary": "Implementation\u0020of\u0020PSR\u002D18\u0020NetworkExceptionInterface.",
            "url": "classes/MStilkerich-CardDavClient-Exception-NetworkException.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Exception\\NetworkException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Exception-NetworkException.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Exception\\NetworkException\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "Returns\u0020the\u0020request.",
            "url": "classes/MStilkerich-CardDavClient-Exception-NetworkException.html#method_getRequest"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Exception\\NetworkException\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Exception-NetworkException.html#property_request"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Exception\\XmlParseException",
            "name": "XmlParseException",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Exception-XmlParseException.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapter",
            "name": "HttpClientAdapter",
            "summary": "Abstract\u0020base\u0020class\u0020for\u0020the\u0020internal\u0020HTTP\u0020client\u0020adapter.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapter.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapter\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "Sends\u0020an\u0020HTTP\u0020request\u0020and\u0020returns\u0020a\u0020PSR\u002D7\u0020response.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapter.html#method_sendRequest"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapter\u003A\u003AcheckSameDomainAsBase\u0028\u0029",
            "name": "checkSameDomainAsBase",
            "summary": "Checks\u0020whether\u0020the\u0020given\u0020URI\u0020has\u0020the\u0020same\u0020domain\u0020as\u0020the\u0020base\u0020URI\u0020of\u0020this\u0020HTTP\u0020client.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapter.html#method_checkSameDomainAsBase"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapter\u003A\u003AgetDomainFromSubdomain\u0028\u0029",
            "name": "getDomainFromSubdomain",
            "summary": "Extracts\u0020the\u0020domain\u0020name\u0020from\u0020a\u0020subdomain.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapter.html#method_getDomainFromSubdomain"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapter\u003A\u003A\u0024baseUri",
            "name": "baseUri",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapter.html#property_baseUri"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle",
            "name": "HttpClientAdapterGuzzle",
            "summary": "Adapter\u0020for\u0020the\u0020Guzzle\u0020HTTP\u0020client\u0020library.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020HttpClientAdapterGuzzle\u0020object.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "Sends\u0020a\u0020PSR\u002D7\u0020request\u0020and\u0020returns\u0020a\u0020PSR\u002D7\u0020response.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#method_sendRequest"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003AcheckSabreCurlIncompatibility\u0028\u0029",
            "name": "checkSabreCurlIncompatibility",
            "summary": "Checks\u0020if\u0020a\u0020request\u0020was\u0020rejected\u0020because\u0020of\u0020an\u0020incompatibility\u0020between\u0020curl\u0020and\u0020sabre\/dav.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#method_checkSabreCurlIncompatibility"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003AprepareGuzzleOptions\u0028\u0029",
            "name": "prepareGuzzleOptions",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#method_prepareGuzzleOptions"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003AgetSupportedAuthSchemes\u0028\u0029",
            "name": "getSupportedAuthSchemes",
            "summary": "Extracts\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020a\u0020WWW\u002DAuthenticate\u0020header.",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#method_getSupportedAuthSchemes"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003AGUZZLE_KNOWN_AUTHSCHEMES",
            "name": "GUZZLE_KNOWN_AUTHSCHEMES",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#constant_GUZZLE_KNOWN_AUTHSCHEMES"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#property_client"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#property_username"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#property_password"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003A\u0024authScheme",
            "name": "authScheme",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#property_authScheme"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003A\u0024failedAuthSchemes",
            "name": "failedAuthSchemes",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#property_failedAuthSchemes"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\HttpClientAdapterGuzzle\u003A\u003A\u0024schemeToCurlOpt",
            "name": "schemeToCurlOpt",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-HttpClientAdapterGuzzle.html#property_schemeToCurlOpt"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Discovery",
            "name": "Discovery",
            "summary": "Class\u0020Discovery\u0020\u002D\u0020Provides\u0020a\u0020service\u0020to\u0020discovery\u0020the\u0020addressbooks\u0020for\u0020a\u0020CardDAV\u0020account.",
            "url": "classes/MStilkerich-CardDavClient-Services-Discovery.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Discovery\u003A\u003AdiscoverAddressbooks\u0028\u0029",
            "name": "discoverAddressbooks",
            "summary": "Discover\u0020the\u0020addressbooks\u0020for\u0020a\u0020CardDAV\u0020account.",
            "url": "classes/MStilkerich-CardDavClient-Services-Discovery.html#method_discoverAddressbooks"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Discovery\u003A\u003AdiscoverServers\u0028\u0029",
            "name": "discoverServers",
            "summary": "Discovers\u0020the\u0020CardDAV\u0020service\u0020for\u0020the\u0020given\u0020domain\u0020using\u0020DNS\u0020SRV\u0020lookups.",
            "url": "classes/MStilkerich-CardDavClient-Services-Discovery.html#method_discoverServers"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Discovery\u003A\u003AorderDnsRecords\u0028\u0029",
            "name": "orderDnsRecords",
            "summary": "Orders\u0020DNS\u0020records\u0020by\u0020their\u0020prio\u0020and\u0020weight.",
            "url": "classes/MStilkerich-CardDavClient-Services-Discovery.html#method_orderDnsRecords"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Discovery\u003A\u003AdiscoverContextPath\u0028\u0029",
            "name": "discoverContextPath",
            "summary": "Provides\u0020a\u0020list\u0020of\u0020URIs\u0020to\u0020check\u0020for\u0020discovering\u0020the\u0020location\u0020of\u0020the\u0020CardDAV\u0020service.",
            "url": "classes/MStilkerich-CardDavClient-Services-Discovery.html#method_discoverContextPath"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Discovery\u003A\u003AKNOWN_SERVERS",
            "name": "KNOWN_SERVERS",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-Discovery.html#constant_KNOWN_SERVERS"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Sync",
            "name": "Sync",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-Sync.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Sync\u003A\u003Asynchronize\u0028\u0029",
            "name": "synchronize",
            "summary": "Performs\u0020a\u0020synchronization\u0020of\u0020the\u0020given\u0020addressbook.",
            "url": "classes/MStilkerich-CardDavClient-Services-Sync.html#method_synchronize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Sync\u003A\u003AsynchronizeOneBatch\u0028\u0029",
            "name": "synchronizeOneBatch",
            "summary": "Performs\u0020a\u0020synchronization\u0020of\u0020the\u0020given\u0020addressbook\u0020for\u0020one\u0020synchronization\u0020chunk\u0020as\u0020dicated\u0020by\u0020the\u0020server.",
            "url": "classes/MStilkerich-CardDavClient-Services-Sync.html#method_synchronizeOneBatch"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Sync\u003A\u003AsyncCollection\u0028\u0029",
            "name": "syncCollection",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-Sync.html#method_syncCollection"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Sync\u003A\u003AdetermineChangesViaETags\u0028\u0029",
            "name": "determineChangesViaETags",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-Sync.html#method_determineChangesViaETags"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\Sync\u003A\u003AmultiGetChanges\u0028\u0029",
            "name": "multiGetChanges",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-Sync.html#method_multiGetChanges"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncHandler",
            "name": "SyncHandler",
            "summary": "Interface\u0020for\u0020application\u002Dlevel\u0020synchronization\u0020handler.",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncHandler.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncHandler\u003A\u003AaddressObjectChanged\u0028\u0029",
            "name": "addressObjectChanged",
            "summary": "This\u0020method\u0020is\u0020called\u0020for\u0020each\u0020changed\u0020address\u0020object,\u0020including\u0020new\u0020address\u0020objects.",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncHandler.html#method_addressObjectChanged"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncHandler\u003A\u003AaddressObjectDeleted\u0028\u0029",
            "name": "addressObjectDeleted",
            "summary": "This\u0020method\u0020is\u0020called\u0020for\u0020each\u0020deleted\u0020address\u0020object.",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncHandler.html#method_addressObjectDeleted"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncHandler\u003A\u003AgetExistingVCardETags\u0028\u0029",
            "name": "getExistingVCardETags",
            "summary": "Provides\u0020the\u0020URIs\u0020and\u0020ETags\u0020of\u0020all\u0020VCards\u0020existing\u0020locally.",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncHandler.html#method_getExistingVCardETags"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncHandler\u003A\u003AfinalizeSync\u0028\u0029",
            "name": "finalizeSync",
            "summary": "Called\u0020upon\u0020completion\u0020of\u0020the\u0020synchronization\u0020process\u0020to\u0020enable\u0020the\u0020handler\u0020to\nperform\u0020final\u0020actions\u0020if\u0020needed.",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncHandler.html#method_finalizeSync"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncResult",
            "name": "SyncResult",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncResult.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncResult.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncResult\u003A\u003AcreateVCards\u0028\u0029",
            "name": "createVCards",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncResult.html#method_createVCards"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncResult\u003A\u003A\u0024syncToken",
            "name": "syncToken",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncResult.html#property_syncToken"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncResult\u003A\u003A\u0024syncAgain",
            "name": "syncAgain",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncResult.html#property_syncAgain"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncResult\u003A\u003A\u0024deletedObjects",
            "name": "deletedObjects",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncResult.html#property_deletedObjects"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services\\SyncResult\u003A\u003A\u0024changedObjects",
            "name": "changedObjects",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-Services-SyncResult.html#property_changedObjects"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavCollection",
            "name": "WebDavCollection",
            "summary": "Represents\u0020a\u0020collection\u0020on\u0020a\u0020WebDAV\u0020server.",
            "url": "classes/MStilkerich-CardDavClient-WebDavCollection.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavCollection\u003A\u003AgetSyncToken\u0028\u0029",
            "name": "getSyncToken",
            "summary": "Returns\u0020the\u0020sync\u0020token\u0020of\u0020this\u0020collection.",
            "url": "classes/MStilkerich-CardDavClient-WebDavCollection.html#method_getSyncToken"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavCollection\u003A\u003AsupportsSyncCollection\u0028\u0029",
            "name": "supportsSyncCollection",
            "summary": "Queries\u0020whether\u0020the\u0020server\u0020supports\u0020the\u0020sync\u002Dcollection\u0020REPORT\u0020on\u0020this\u0020collection.",
            "url": "classes/MStilkerich-CardDavClient-WebDavCollection.html#method_supportsSyncCollection"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavCollection\u003A\u003AgetChildren\u0028\u0029",
            "name": "getChildren",
            "summary": "Returns\u0020the\u0020child\u0020resources\u0020of\u0020this\u0020collection.",
            "url": "classes/MStilkerich-CardDavClient-WebDavCollection.html#method_getChildren"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavCollection\u003A\u003AgetNeededCollectionPropertyNames\u0028\u0029",
            "name": "getNeededCollectionPropertyNames",
            "summary": "Provides\u0020the\u0020list\u0020of\u0020property\u0020names\u0020that\u0020should\u0020be\u0020requested\u0020upon\u0020call\u0020of\u0020refreshProperties\u0028\u0029.",
            "url": "classes/MStilkerich-CardDavClient-WebDavCollection.html#method_getNeededCollectionPropertyNames"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavCollection\u003A\u003AsupportsReport\u0028\u0029",
            "name": "supportsReport",
            "summary": "Checks\u0020if\u0020the\u0020server\u0020supports\u0020the\u0020given\u0020REPORT\u0020on\u0020this\u0020collection.",
            "url": "classes/MStilkerich-CardDavClient-WebDavCollection.html#method_supportsReport"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavCollection\u003A\u003APROPNAMES",
            "name": "PROPNAMES",
            "summary": "List\u0020of\u0020properties\u0020to\u0020query\u0020in\u0020refreshProperties\u0028\u0029\u0020and\u0020returned\u0020by\u0020getProperties\u0028\u0029.",
            "url": "classes/MStilkerich-CardDavClient-WebDavCollection.html#constant_PROPNAMES"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource",
            "name": "WebDavResource",
            "summary": "Represents\u0020a\u0020resource\u0020on\u0020a\u0020WebDAV\u0020server.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AcreateInstance\u0028\u0029",
            "name": "createInstance",
            "summary": "Factory\u0020for\u0020WebDavResource\u0020objects.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_createInstance"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020WebDavResource\u0020object.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AgetProperties\u0028\u0029",
            "name": "getProperties",
            "summary": "Returns\u0020the\u0020standard\u0020WebDAV\u0020properties\u0020for\u0020this\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_getProperties"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003ArefreshProperties\u0028\u0029",
            "name": "refreshProperties",
            "summary": "Forces\u0020a\u0020refresh\u0020of\u0020the\u0020cached\u0020standard\u0020WebDAV\u0020properties\u0020for\u0020this\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_refreshProperties"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "Allows\u0020to\u0020serialize\u0020WebDavResource\u0020object\u0020to\u0020JSON.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_jsonSerialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AgetAccount\u0028\u0029",
            "name": "getAccount",
            "summary": "Returns\u0020the\u0020Account\u0020this\u0020resource\u0020belongs\u0020to.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_getAccount"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "Provides\u0020a\u0020CardDavClient\u0020object\u0020to\u0020interact\u0020with\u0020the\u0020server\u0020for\u0020this\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_getClient"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AgetUri\u0028\u0029",
            "name": "getUri",
            "summary": "Returns\u0020the\u0020URI\u0020of\u0020this\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_getUri"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AgetUriPath\u0028\u0029",
            "name": "getUriPath",
            "summary": "Returns\u0020the\u0020path\u0020component\u0020of\u0020the\u0020URI\u0020of\u0020this\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_getUriPath"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AgetBasename\u0028\u0029",
            "name": "getBasename",
            "summary": "Returns\u0020the\u0020basename\u0020\u0028last\u0020path\u0020component\u0029\u0020of\u0020the\u0020URI\u0020of\u0020this\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_getBasename"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AdownloadResource\u0028\u0029",
            "name": "downloadResource",
            "summary": "Downloads\u0020the\u0020content\u0020of\u0020a\u0020given\u0020resource.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_downloadResource"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003AgetNeededCollectionPropertyNames\u0028\u0029",
            "name": "getNeededCollectionPropertyNames",
            "summary": "Provides\u0020the\u0020list\u0020of\u0020property\u0020names\u0020that\u0020should\u0020be\u0020requested\u0020upon\u0020call\u0020of\u0020refreshProperties\u0028\u0029.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#method_getNeededCollectionPropertyNames"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003APROPNAMES",
            "name": "PROPNAMES",
            "summary": "List\u0020of\u0020properties\u0020to\u0020query\u0020in\u0020refreshProperties\u0028\u0029\u0020and\u0020returned\u0020by\u0020getProperties\u0028\u0029.",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#constant_PROPNAMES"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "URI\u0020of\u0020the\u0020resource",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#property_uri"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003A\u0024props",
            "name": "props",
            "summary": "Cached\u0020WebDAV\u0020properties\u0020of\u0020the\u0020resource",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#property_props"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003A\u0024account",
            "name": "account",
            "summary": "The\u0020CardDAV\u0020account\u0020this\u0020resource\u0020is\u0020associated\/accessible\u0020with",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#property_account"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\WebDavResource\u003A\u003A\u0024client",
            "name": "client",
            "summary": "CardDavClient\u0020object\u0020for\u0020the\u0020account\u0027s\u0020base\u0020URI",
            "url": "classes/MStilkerich-CardDavClient-WebDavResource.html#property_client"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Deserializers",
            "name": "Deserializers",
            "summary": "Class\u0020Deserializers.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Deserializers.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Deserializers\u003A\u003AdeserializeHrefSingle\u0028\u0029",
            "name": "deserializeHrefSingle",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Deserializers.html#method_deserializeHrefSingle"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Deserializers\u003A\u003AdeserializeHrefMulti\u0028\u0029",
            "name": "deserializeHrefMulti",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Deserializers.html#method_deserializeHrefMulti"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Deserializers\u003A\u003AdeserializeSupportedReportSet\u0028\u0029",
            "name": "deserializeSupportedReportSet",
            "summary": "Deserializes\u0020XML\u0020DAV\u003Asupported\u002Dreport\u002Dset\u0020elements\u0020to\u0020an\u0020array.\u0020\u0028RFC3253\u0029",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Deserializers.html#method_deserializeSupportedReportSet"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Deserializers\u003A\u003AdeserializeToAttributes\u0028\u0029",
            "name": "deserializeToAttributes",
            "summary": "Deserializes\u0020an\u0020XML\u0020element\u0020to\u0020an\u0020array\u0020of\u0020its\u0020attributes,\u0020discarding\u0020its\u0020contents.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Deserializers.html#method_deserializeToAttributes"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Deserializers\u003A\u003AdeserializeSupportedAddrData\u0028\u0029",
            "name": "deserializeSupportedAddrData",
            "summary": "Deserializes\u0020a\u0020CARDDAV\u003Asupported\u002Daddress\u002Ddata\u0020element\u0020\u0028RFC\u00206352\u0029.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Deserializers.html#method_deserializeSupportedAddrData"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames",
            "name": "ElementNames",
            "summary": "Class\u0020ElementNames.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ANSDAV",
            "name": "NSDAV",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_NSDAV"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ANSCARDDAV",
            "name": "NSCARDDAV",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_NSCARDDAV"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ANSCS",
            "name": "NSCS",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_NSCS"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ACURUSRPRINC",
            "name": "CURUSRPRINC",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_CURUSRPRINC"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AABOOK_HOME",
            "name": "ABOOK_HOME",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_ABOOK_HOME"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ADISPNAME",
            "name": "DISPNAME",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_DISPNAME"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ARESTYPE",
            "name": "RESTYPE",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_RESTYPE"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ARESTYPE_COLL",
            "name": "RESTYPE_COLL",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_RESTYPE_COLL"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ARESTYPE_ABOOK",
            "name": "RESTYPE_ABOOK",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_RESTYPE_ABOOK"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AGETCTAG",
            "name": "GETCTAG",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_GETCTAG"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AGETETAG",
            "name": "GETETAG",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_GETETAG"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AADD_MEMBER",
            "name": "ADD_MEMBER",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_ADD_MEMBER"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ASUPPORTED_REPORT_SET",
            "name": "SUPPORTED_REPORT_SET",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_SUPPORTED_REPORT_SET"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ASUPPORTED_REPORT",
            "name": "SUPPORTED_REPORT",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_SUPPORTED_REPORT"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AREPORT",
            "name": "REPORT",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_REPORT"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AREPORT_SYNCCOLL",
            "name": "REPORT_SYNCCOLL",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_REPORT_SYNCCOLL"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AREPORT_MULTIGET",
            "name": "REPORT_MULTIGET",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_REPORT_MULTIGET"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AREPORT_QUERY",
            "name": "REPORT_QUERY",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_REPORT_QUERY"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ASYNCTOKEN",
            "name": "SYNCTOKEN",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_SYNCTOKEN"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ASYNCLEVEL",
            "name": "SYNCLEVEL",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_SYNCLEVEL"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ASUPPORTED_ADDRDATA",
            "name": "SUPPORTED_ADDRDATA",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_SUPPORTED_ADDRDATA"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AADDRDATA",
            "name": "ADDRDATA",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_ADDRDATA"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AADDRDATATYPE",
            "name": "ADDRDATATYPE",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_ADDRDATATYPE"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AVCFPROP",
            "name": "VCFPROP",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_VCFPROP"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AABOOK_DESC",
            "name": "ABOOK_DESC",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_ABOOK_DESC"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AMAX_RESSIZE",
            "name": "MAX_RESSIZE",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_MAX_RESSIZE"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AMULTISTATUS",
            "name": "MULTISTATUS",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_MULTISTATUS"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ARESPONSE",
            "name": "RESPONSE",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_RESPONSE"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ASTATUS",
            "name": "STATUS",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_STATUS"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003APROPFIND",
            "name": "PROPFIND",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_PROPFIND"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003APROPSTAT",
            "name": "PROPSTAT",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_PROPSTAT"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003APROP",
            "name": "PROP",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_PROP"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AHREF",
            "name": "HREF",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_HREF"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ALIMIT",
            "name": "LIMIT",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_LIMIT"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ANRESULTS",
            "name": "NRESULTS",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_NRESULTS"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ASUPPORTED_FILTER",
            "name": "SUPPORTED_FILTER",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_SUPPORTED_FILTER"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AFILTER",
            "name": "FILTER",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_FILTER"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003APROPFILTER",
            "name": "PROPFILTER",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_PROPFILTER"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003APARAMFILTER",
            "name": "PARAMFILTER",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_PARAMFILTER"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003ATEXTMATCH",
            "name": "TEXTMATCH",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_TEXTMATCH"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ElementNames\u003A\u003AISNOTDEFINED",
            "name": "ISNOTDEFINED",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ElementNames.html#constant_ISNOTDEFINED"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Filter",
            "name": "Filter",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020urn\u003Aietf\u003Aparams\u003Axml\u003Ans\u003Acarddav\u003Afilter\u0020elements\u0020as\u0020PHP\u0020objects.\u0020\u0028RFC\u00206352\u0029",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Filter.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Filter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020Filter\u0020consisting\u0020of\u0020zero\u0020or\u0020more\u0020PropFilter\u0020elements.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Filter.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Filter\u003A\u003AxmlSerialize\u0028\u0029",
            "name": "xmlSerialize",
            "summary": "This\u0020function\u0020encodes\u0020the\u0020elements\u0020value\u0020\u0028not\u0020the\u0020element\u0020itself\u0021\u0029\u0020to\u0020the\u0020given\u0020XML\u0020writer.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Filter.html#method_xmlSerialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Filter\u003A\u003AxmlAttributes\u0028\u0029",
            "name": "xmlAttributes",
            "summary": "Produces\u0020a\u0020list\u0020of\u0020attributes\u0020for\u0020this\u0020filter\u0020suitable\u0020to\u0020pass\u0020to\u0020a\u0020Sabre\u0020XML\u0020Writer.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Filter.html#method_xmlAttributes"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Filter\u003A\u003A\u0024testType",
            "name": "testType",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Filter.html#property_testType"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Filter\u003A\u003A\u0024propFilters",
            "name": "propFilters",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Filter.html#property_propFilters"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Multistatus",
            "name": "Multistatus",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020DAV\u003Amultistatus\u0020elements\u0020as\u0020PHP\u0020objects.\u0020\u0028RFC\u00204918\u0029",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Multistatus.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Multistatus\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Multistatus.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Multistatus\u003A\u003AxmlDeserialize\u0028\u0029",
            "name": "xmlDeserialize",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Multistatus.html#method_xmlDeserialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Multistatus\u003A\u003A\u0024synctoken",
            "name": "synctoken",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Multistatus.html#property_synctoken"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Multistatus\u003A\u003A\u0024responses",
            "name": "responses",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Multistatus.html#property_responses"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ParamFilter",
            "name": "ParamFilter",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020urn\u003Aietf\u003Aparams\u003Axml\u003Ans\u003Acarddav\u003Aparam\u002Dfilter\u0020elements\u0020as\u0020PHP\u0020objects.\u0020\u0028RFC\u00206352\u0029",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ParamFilter.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ParamFilter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020ParamFilter\u0020element.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ParamFilter.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ParamFilter\u003A\u003AxmlSerialize\u0028\u0029",
            "name": "xmlSerialize",
            "summary": "This\u0020function\u0020encodes\u0020the\u0020elements\u0020value\u0020\u0028not\u0020the\u0020element\u0020itself\u0021\u0029\u0020to\u0020the\u0020given\u0020XML\u0020writer.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ParamFilter.html#method_xmlSerialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ParamFilter\u003A\u003AxmlSerializeElement\u0028\u0029",
            "name": "xmlSerializeElement",
            "summary": "This\u0020function\u0020serializes\u0020the\u0020full\u0020element\u0020to\u0020the\u0020given\u0020XML\u0020writer.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ParamFilter.html#method_xmlSerializeElement"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ParamFilter\u003A\u003AxmlAttributes\u0028\u0029",
            "name": "xmlAttributes",
            "summary": "Produces\u0020a\u0020list\u0020of\u0020attributes\u0020for\u0020this\u0020filter\u0020suitable\u0020to\u0020pass\u0020to\u0020a\u0020Sabre\u0020XML\u0020Writer.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ParamFilter.html#method_xmlAttributes"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ParamFilter\u003A\u003A\u0024param",
            "name": "param",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ParamFilter.html#property_param"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ParamFilter\u003A\u003A\u0024filter",
            "name": "filter",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ParamFilter.html#property_filter"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Prop",
            "name": "Prop",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020DAV\u003Aprop\u0020elements\u0020as\u0020PHP\u0020objects.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Prop.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Prop\u003A\u003AxmlDeserialize\u0028\u0029",
            "name": "xmlDeserialize",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Prop.html#method_xmlDeserialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Prop\u003A\u003AstoreProperty\u0028\u0029",
            "name": "storeProperty",
            "summary": "Processes\u0020a\u0020deserialized\u0020prop\u0020child\u0020element\u0020and\u0020stores\u0020the\u0020result\u0020if\u0020known.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Prop.html#method_storeProperty"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Prop\u003A\u003APROP_DESERIALIZERS",
            "name": "PROP_DESERIALIZERS",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Prop.html#constant_PROP_DESERIALIZERS"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Prop\u003A\u003A\u0024props",
            "name": "props",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Prop.html#property_props"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Propstat",
            "name": "Propstat",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020DAV\u003Apropstat\u0020elements\u0020as\u0020PHP\u0020objects.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Propstat.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Propstat\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Propstat.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Propstat\u003A\u003AxmlDeserialize\u0028\u0029",
            "name": "xmlDeserialize",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Propstat.html#method_xmlDeserialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Propstat\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Propstat.html#property_status"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Propstat\u003A\u003A\u0024prop",
            "name": "prop",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Propstat.html#property_prop"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Response",
            "name": "Response",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020DAV\u003Aresponse\u0020elements\u0020as\u0020PHP\u0020objects.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Response.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\Response\u003A\u003AxmlDeserialize\u0028\u0029",
            "name": "xmlDeserialize",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-Response.html#method_xmlDeserialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ResponsePropstat",
            "name": "ResponsePropstat",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020DAV\u003Aresponse\u0020elements\u0020with\u0020propstat\u0020children\u0020as\u0020PHP\u0020objects.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ResponsePropstat.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ResponsePropstat\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ResponsePropstat.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ResponsePropstat\u003A\u003A\u0024href",
            "name": "href",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ResponsePropstat.html#property_href"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ResponsePropstat\u003A\u003A\u0024propstat",
            "name": "propstat",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ResponsePropstat.html#property_propstat"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ResponseStatus",
            "name": "ResponseStatus",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020DAV\u003Aresponse\u0020elements\u0020with\u0020status\u0020children\u0020as\u0020PHP\u0020objects.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ResponseStatus.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ResponseStatus\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ResponseStatus.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ResponseStatus\u003A\u003A\u0024hrefs",
            "name": "hrefs",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ResponseStatus.html#property_hrefs"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\ResponseStatus\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-ResponseStatus.html#property_status"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch",
            "name": "TextMatch",
            "summary": "Class\u0020to\u0020represent\u0020XML\u0020urn\u003Aietf\u003Aparams\u003Axml\u003Ans\u003Acarddav\u003Atext\u002Dmatch\u0020elements\u0020as\u0020PHP\u0020objects.\u0020\u0028RFC\u00206352\u0029",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020TextMatch\u0020element.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html#method___construct"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch\u003A\u003AxmlSerialize\u0028\u0029",
            "name": "xmlSerialize",
            "summary": "This\u0020function\u0020encodes\u0020the\u0020elements\u0020value\u0020\u0028not\u0020the\u0020element\u0020itself\u0021\u0029\u0020to\u0020the\u0020given\u0020XML\u0020writer.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html#method_xmlSerialize"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch\u003A\u003AxmlSerializeElement\u0028\u0029",
            "name": "xmlSerializeElement",
            "summary": "This\u0020function\u0020serializes\u0020the\u0020full\u0020element\u0020to\u0020the\u0020given\u0020XML\u0020writer.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html#method_xmlSerializeElement"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch\u003A\u003AxmlAttributes\u0028\u0029",
            "name": "xmlAttributes",
            "summary": "Produces\u0020a\u0020list\u0020of\u0020attributes\u0020for\u0020this\u0020filter\u0020suitable\u0020to\u0020pass\u0020to\u0020a\u0020Sabre\u0020XML\u0020Writer.",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html#method_xmlAttributes"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch\u003A\u003A\u0024collation",
            "name": "collation",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html#property_collation"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch\u003A\u003A\u0024invertMatch",
            "name": "invertMatch",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html#property_invertMatch"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch\u003A\u003A\u0024matchType",
            "name": "matchType",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html#property_matchType"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements\\TextMatch\u003A\u003A\u0024needle",
            "name": "needle",
            "summary": "",
            "url": "classes/MStilkerich-CardDavClient-XmlElements-TextMatch.html#property_needle"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient",
            "name": "CardDavClient",
            "summary": "",
            "url": "namespaces/mstilkerich-carddavclient.html"
        },                {
            "fqsen": "\\MStilkerich",
            "name": "MStilkerich",
            "summary": "",
            "url": "namespaces/mstilkerich.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/mstilkerich-carddavclient-exception.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/mstilkerich-carddavclient-services.html"
        },                {
            "fqsen": "\\MStilkerich\\CardDavClient\\XmlElements",
            "name": "XmlElements",
            "summary": "",
            "url": "namespaces/mstilkerich-carddavclient-xmlelements.html"
        }            ]
);
